# Travis build integration.
# https://docs.travis-ci.com/

language: c

matrix:
  include:
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: amd64
      compiler: gcc

    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: clang
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc

script: ./tests/travis.sh
